language: go

go:
  - 1.3
  - tip
install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get gopkg.in/check.v1
  - go get github.com/flosch/pongo2
script:
  - go test -v -covermode=count -coverprofile=coverage.out
